// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgFMYagvZdfP_RjCh1j4WAHc645dbdXdA',
    appId: '1:226815525805:web:51b1c0b108dbe710f25724',
    messagingSenderId: '226815525805',
    projectId: 'ecommerceapp-a7637',
    authDomain: 'ecommerceapp-a7637.firebaseapp.com',
    storageBucket: 'ecommerceapp-a7637.firebasestorage.app',
    measurementId: 'G-03BPXT22W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfiylyDxTSAG3-s5WDPDKjZiUTKeius9c',
    appId: '1:226815525805:android:5583c73931818e46f25724',
    messagingSenderId: '226815525805',
    projectId: 'ecommerceapp-a7637',
    storageBucket: 'ecommerceapp-a7637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ2o6Mpyc7lmlw2hpj15S2CsQxT5hAdLY',
    appId: '1:226815525805:ios:3e24bd714b6f7eb5f25724',
    messagingSenderId: '226815525805',
    projectId: 'ecommerceapp-a7637',
    storageBucket: 'ecommerceapp-a7637.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
